#!/usr/bin/env python3
"""Analyze runtime exit reason mapping gap between live-paper and backtest.

Inputs:
  - strategyless exit audit JSON (recommended: segmented live log variant)
Output:
  - reason/market gap report with concrete next-step hints.
"""

from __future__ import annotations

import argparse
import json
import re
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Iterable, List, Tuple

from _script_common import dump_json, resolve_repo_path


def parse_args(argv=None) -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--audit-json",
        default="build/Release/logs/strategyless_exit_audit_5set_20260224_sell_lifecycle_v4_segmented.json",
        help="Input audit JSON path generated by collect_strategyless_exit_audit.py",
    )
    parser.add_argument(
        "--output-json",
        default="build/Release/logs/exit_reason_mapping_gap_20260224_v1.json",
        help="Output report path.",
    )
    parser.add_argument(
        "--top-n",
        type=int,
        default=20,
        help="Top N rows for detailed delta tables.",
    )
    parser.add_argument(
        "--min-live-exits",
        type=int,
        default=0,
        help="Minimum live exit count required for mapping-gap conclusion (0 disables the threshold).",
    )
    parser.add_argument(
        "--min-backtest-exits",
        type=int,
        default=0,
        help="Minimum backtest exit count required for mapping-gap conclusion (0 disables the threshold).",
    )
    return parser.parse_args(argv)


def normalize_reason(reason: str) -> str:
    value = str(reason or "").strip()
    return value if value else "unknown"


def normalize_market(market: str) -> str:
    value = str(market or "").strip()
    return value if value else "unknown"


def canonical_reason(reason: str) -> str:
    raw = normalize_reason(reason).strip().lower().replace("-", "_")
    aliases = {
        "stoploss": "STOP_LOSS",
        "stop_loss": "STOP_LOSS",
        "takeprofit1": "TAKE_PROFIT_1",
        "take_profit_1": "TAKE_PROFIT_1",
        "takeprofit2": "TAKE_PROFIT_2",
        "take_profit": "TAKE_PROFIT_2",
        "take_profit_2": "TAKE_PROFIT_2",
        "takeprofitfullduetominorder": "TAKE_PROFIT_FULL_DUE_TO_MIN_ORDER",
        "take_profit_full_due_to_min_order": "TAKE_PROFIT_FULL_DUE_TO_MIN_ORDER",
        "strategyexit": "STRATEGY_OR_RISK_EXIT",
        "strategy_exit": "STRATEGY_OR_RISK_EXIT",
        "riskmanagerexit": "STRATEGY_OR_RISK_EXIT",
        "risk_manager_exit": "STRATEGY_OR_RISK_EXIT",
        "backtesteod": "BACKTEST_EOD",
        "backtest_eod": "BACKTEST_EOD",
        "unknown": "UNKNOWN",
    }
    if raw in aliases:
        return aliases[raw]
    return raw.upper()


def parse_dataset_market(dataset_name: str) -> str:
    # Expected: upbit_KRW_BTC_1m_12000.csv -> KRW-BTC
    name = str(dataset_name or "").strip()
    base = Path(name).name
    stem = base[:-4] if base.lower().endswith(".csv") else base
    tokens = stem.split("_")
    if len(tokens) >= 3 and tokens[0].lower() == "upbit":
        return f"{tokens[1]}-{tokens[2]}"
    return "unknown"


def load_backtest_market_reason_counts_from_runtime_samples(dataset_results: List[Any]) -> Dict[str, int]:
    counts: Dict[str, int] = {}
    for item in dataset_results:
        if not isinstance(item, dict):
            continue
        market = parse_dataset_market(str(item.get("dataset", "")))
        runtime = item.get("runtime_trade_distribution", {})
        if not isinstance(runtime, dict):
            continue
        reason_counts = runtime.get("runtime_exit_reason_counts_in_samples", {})
        if not isinstance(reason_counts, dict):
            continue
        for reason, count in reason_counts.items():
            key = f"{normalize_market(market)}|{normalize_reason(str(reason))}"
            counts[key] = counts.get(key, 0) + int(count)
    return counts


def load_backtest_market_reason_counts_from_dataset_exit_counts(dataset_results: List[Any]) -> Dict[str, int]:
    counts: Dict[str, int] = {}
    for item in dataset_results:
        if not isinstance(item, dict):
            continue
        market = parse_dataset_market(str(item.get("dataset", "")))
        reason_counts = item.get("exit_reason_counts", {})
        if not isinstance(reason_counts, dict):
            continue
        for reason, count in reason_counts.items():
            key = f"{normalize_market(market)}|{normalize_reason(str(reason))}"
            counts[key] = counts.get(key, 0) + int(count)
    return counts


def parse_live_market_reason_counts_from_log(log_path: Path) -> Dict[str, int]:
    counts: Dict[str, int] = {}
    if not log_path.exists():
        return counts
    pattern = re.compile(r"Position exited:\s*([A-Z0-9\-]+)\s*\|.*?\|\s*reason=([A-Za-z0-9_]+)")
    for line in log_path.read_text(encoding="utf-8", errors="replace").splitlines():
        m = pattern.search(line)
        if not m:
            continue
        market = normalize_market(m.group(1))
        reason = normalize_reason(m.group(2))
        key = f"{market}|{reason}"
        counts[key] = counts.get(key, 0) + 1
    return counts


def load_live_market_reason_counts_from_audit(audit: Dict[str, Any]) -> Tuple[Dict[str, int], str]:
    snapshot = audit.get("live_exit_reason_snapshot")
    if not isinstance(snapshot, dict):
        return {}, "none"
    market_reason = snapshot.get("exit_market_reason_counts")
    if isinstance(market_reason, dict):
        parsed: Dict[str, int] = {}
        for key, count in market_reason.items():
            try:
                parsed[str(key)] = int(count)
            except Exception:
                parsed[str(key)] = 0
        return parsed, "audit_snapshot"
    return {}, "none"


def canonicalize_market_reason_counter(counter: Dict[str, int]) -> Dict[str, int]:
    out: Dict[str, int] = {}
    for key, count in counter.items():
        market, reason = "unknown", "unknown"
        if "|" in key:
            market, reason = key.split("|", 1)
        norm_market = normalize_market(market)
        norm_reason = canonical_reason(reason)
        mapped_key = f"{norm_market}|{norm_reason}"
        out[mapped_key] = out.get(mapped_key, 0) + int(count)
    return out


def split_market_reason(counter: Dict[str, int]) -> Tuple[Dict[str, int], Dict[str, int]]:
    market_counts: Counter = Counter()
    reason_counts: Counter = Counter()
    for key, count in counter.items():
        market, reason = "unknown", "unknown"
        if "|" in key:
            market, reason = key.split("|", 1)
        market_counts[normalize_market(market)] += int(count)
        reason_counts[normalize_reason(reason)] += int(count)
    return dict(market_counts), dict(reason_counts)


def build_delta_rows(
    live_counter: Dict[str, int],
    backtest_counter: Dict[str, int],
    top_n: int,
) -> List[Dict[str, Any]]:
    keys = sorted(set(live_counter.keys()) | set(backtest_counter.keys()))
    live_total = float(sum(int(v) for v in live_counter.values()))
    backtest_total = float(sum(int(v) for v in backtest_counter.values()))
    rows: List[Dict[str, Any]] = []
    for key in keys:
        live_count = int(live_counter.get(key, 0))
        backtest_count = int(backtest_counter.get(key, 0))
        rows.append(
            {
                "key": key,
                "live_count": live_count,
                "backtest_count": backtest_count,
                "delta_count": live_count - backtest_count,
                "live_ratio": (live_count / live_total) if live_total > 0 else 0.0,
                "backtest_ratio": (backtest_count / backtest_total) if backtest_total > 0 else 0.0,
            }
        )
    rows.sort(
        key=lambda r: (abs(int(r["delta_count"])), abs(float(r["live_ratio"]) - float(r["backtest_ratio"]))),
        reverse=True,
    )
    return rows[: max(1, int(top_n))]


def main(argv=None) -> int:
    args = parse_args(argv)
    audit_path = resolve_repo_path(args.audit_json)
    out_path = resolve_repo_path(args.output_json)
    top_n = max(1, int(args.top_n))
    min_live_exits = max(0, int(args.min_live_exits))
    min_backtest_exits = max(0, int(args.min_backtest_exits))

    if not audit_path.exists():
        raise FileNotFoundError(f"audit json not found: {audit_path}")
    audit = json.loads(audit_path.read_text(encoding="utf-8"))

    dataset_results = audit.get("dataset_results", [])
    if not isinstance(dataset_results, list):
        dataset_results = []

    backtest_runtime_market_reason_counts = load_backtest_market_reason_counts_from_runtime_samples(dataset_results)
    backtest_dataset_exit_market_reason_counts = load_backtest_market_reason_counts_from_dataset_exit_counts(dataset_results)

    # Live runtime sample: parse market|reason pairs from segmented live log.
    live_market_reason_counts, live_source = load_live_market_reason_counts_from_audit(audit)
    live_log_path_raw = (
        (audit.get("live_exit_reason_snapshot") or {}).get("path")
        if isinstance(audit.get("live_exit_reason_snapshot"), dict)
        else None
    )
    live_log_path = resolve_repo_path(str(live_log_path_raw)) if live_log_path_raw else Path("")
    if not live_market_reason_counts:
        live_market_reason_counts = parse_live_market_reason_counts_from_log(live_log_path)
        live_source = "runtime_log_path"

    live_market_reason_counts_canonical = canonicalize_market_reason_counter(live_market_reason_counts)
    backtest_runtime_market_reason_counts_canonical = canonicalize_market_reason_counter(backtest_runtime_market_reason_counts)
    backtest_dataset_exit_market_reason_counts_canonical = canonicalize_market_reason_counter(
        backtest_dataset_exit_market_reason_counts
    )

    runtime_sample_total = int(sum(backtest_runtime_market_reason_counts_canonical.values()))
    dataset_exit_total = int(sum(backtest_dataset_exit_market_reason_counts_canonical.values()))
    if dataset_exit_total > 0:
        backtest_counts_source = "dataset_exit_reason_counts"
        backtest_selected_market_reason_counts_canonical = backtest_dataset_exit_market_reason_counts_canonical
    else:
        backtest_counts_source = "runtime_trade_distribution_samples"
        backtest_selected_market_reason_counts_canonical = backtest_runtime_market_reason_counts_canonical

    live_market_counts, live_reason_counts = split_market_reason(live_market_reason_counts_canonical)
    backtest_market_counts, backtest_reason_counts = split_market_reason(backtest_selected_market_reason_counts_canonical)

    reason_only_live = sorted(set(live_reason_counts.keys()) - set(backtest_reason_counts.keys()))
    reason_only_backtest = sorted(set(backtest_reason_counts.keys()) - set(live_reason_counts.keys()))
    market_only_live = sorted(set(live_market_counts.keys()) - set(backtest_market_counts.keys()))
    market_only_backtest = sorted(set(backtest_market_counts.keys()) - set(live_market_counts.keys()))
    common_markets = sorted(set(live_market_counts.keys()) & set(backtest_market_counts.keys()))

    live_total = int(sum(live_reason_counts.values()))
    backtest_total = int(sum(backtest_reason_counts.values()))
    sample_size_ready = live_total >= min_live_exits and backtest_total >= min_backtest_exits
    comparable = live_total > 0 and backtest_total > 0

    stoploss_vs_backtesteod_signature = (
        int(live_reason_counts.get("STOP_LOSS", 0)) > 0
        and int(backtest_reason_counts.get("BACKTEST_EOD", 0)) > 0
        and int(backtest_reason_counts.get("STOP_LOSS", 0)) == 0
    )
    mapping_gap_observed_raw = (
        stoploss_vs_backtesteod_signature
        or bool(reason_only_live)
        or bool(reason_only_backtest)
        or bool(market_only_live)
        or bool(market_only_backtest)
    )
    mapping_gap_observed = bool(mapping_gap_observed_raw and sample_size_ready)
    overlap_ready = comparable and len(common_markets) > 0

    if not comparable:
        next_step_hint = "collect_more_live_exit_reasons"
    elif not overlap_ready:
        next_step_hint = "collect_live_exits_on_backtest_overlap_markets"
    elif not sample_size_ready:
        next_step_hint = "increase_overlap_exit_samples_before_mapping_decision"
    elif mapping_gap_observed:
        next_step_hint = "narrow_correctness_patch_scope_to_runtime_strategyless_exit_mapping"
    else:
        next_step_hint = "no_material_reason_mapping_gap_detected"

    report = {
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "inputs": {
            "audit_json": str(audit_path),
            "live_runtime_log": str(live_log_path) if live_log_path else "",
            "live_counts_source": live_source,
            "backtest_counts_source": backtest_counts_source,
            "top_n": top_n,
            "min_live_exits": min_live_exits,
            "min_backtest_exits": min_backtest_exits,
        },
        "live": {
            "total_exits": live_total,
            "reason_counts": live_reason_counts,
            "market_counts": live_market_counts,
            "market_reason_counts": live_market_reason_counts_canonical,
        },
        "backtest_runtime_sample": {
            "total_exits": runtime_sample_total,
            "reason_counts": split_market_reason(backtest_runtime_market_reason_counts_canonical)[1],
            "market_counts": split_market_reason(backtest_runtime_market_reason_counts_canonical)[0],
            "market_reason_counts": backtest_runtime_market_reason_counts_canonical,
        },
        "backtest_dataset_exit_counts": {
            "total_exits": dataset_exit_total,
            "reason_counts": split_market_reason(backtest_dataset_exit_market_reason_counts_canonical)[1],
            "market_counts": split_market_reason(backtest_dataset_exit_market_reason_counts_canonical)[0],
            "market_reason_counts": backtest_dataset_exit_market_reason_counts_canonical,
        },
        "backtest_selected": {
            "source": backtest_counts_source,
            "total_exits": backtest_total,
            "reason_counts": backtest_reason_counts,
            "market_counts": backtest_market_counts,
            "market_reason_counts": backtest_selected_market_reason_counts_canonical,
        },
        "raw_reason_snapshot": {
            "live_market_reason_counts": live_market_reason_counts,
            "backtest_runtime_market_reason_counts": backtest_runtime_market_reason_counts,
            "backtest_dataset_exit_market_reason_counts": backtest_dataset_exit_market_reason_counts,
        },
        "gap_analysis": {
            "reason_only_in_live": reason_only_live,
            "reason_only_in_backtest": reason_only_backtest,
            "market_only_in_live": market_only_live,
            "market_only_in_backtest": market_only_backtest,
            "common_markets": common_markets,
            "reason_delta_rows": build_delta_rows(live_reason_counts, backtest_reason_counts, top_n),
            "market_delta_rows": build_delta_rows(live_market_counts, backtest_market_counts, top_n),
            "market_reason_delta_rows": build_delta_rows(
                live_market_reason_counts_canonical,
                backtest_selected_market_reason_counts_canonical,
                top_n,
            ),
        },
        "readiness": {
            "comparable": comparable,
            "overlap_ready": overlap_ready,
            "sample_size_ready": sample_size_ready,
            "min_live_exits": min_live_exits,
            "min_backtest_exits": min_backtest_exits,
            "mapping_gap_observed": mapping_gap_observed,
            "mapping_gap_observed_raw": mapping_gap_observed_raw,
            "mapping_gap_inconclusive_due_to_sample_size": bool(mapping_gap_observed_raw and not sample_size_ready),
            "stoploss_vs_backtesteod_signature": stoploss_vs_backtesteod_signature,
            "next_step_hint": next_step_hint,
        },
    }
    dump_json(out_path, report)
    print(f"[ExitReasonGap] wrote {out_path}")
    print(
        "[ExitReasonGap] comparable="
        f"{str(report['readiness']['comparable']).lower()} "
        "sample_size_ready="
        f"{str(report['readiness']['sample_size_ready']).lower()} "
        "mapping_gap_observed="
        f"{str(report['readiness']['mapping_gap_observed']).lower()} "
        "next_step_hint="
        f"{report['readiness']['next_step_hint']}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
