#!/usr/bin/env python3
"""Validate should-exit parity with explicit must-match vs allowed-difference boundaries.

This validator focuses on exit decision surfaces (reason semantics) rather than
runtime transport differences (timestamp/source/order-id).
"""

from __future__ import annotations

import argparse
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Iterable, List, Tuple

from _script_common import dump_json, load_json_or_none, resolve_repo_path


def parse_args(argv=None) -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--audit-json",
        default="build/Release/logs/strategyless_exit_audit_latest.json",
        help="Input audit JSON generated by collect_strategyless_exit_audit.py",
    )
    parser.add_argument(
        "--output-json",
        default="build/Release/logs/should_exit_parity_report.json",
        help="Output report path.",
    )
    parser.add_argument(
        "--ignore-reasons",
        default="BACKTEST_EOD",
        help="Comma-separated canonical reasons treated as allowed environment-specific difference.",
    )
    parser.add_argument(
        "--critical-reasons",
        default=(
            "STOP_LOSS,TAKE_PROFIT_1,TAKE_PROFIT_2,"
            "TAKE_PROFIT_FULL_DUE_TO_MIN_ORDER,STRATEGY_OR_RISK_EXIT"
        ),
        help="Comma-separated canonical reasons treated as must-match core surface.",
    )
    parser.add_argument(
        "--min-live-core-exits",
        type=int,
        default=3,
        help="Minimum live core exit samples required for conclusive verdict.",
    )
    parser.add_argument(
        "--min-backtest-core-exits",
        type=int,
        default=3,
        help="Minimum backtest core exit samples required for conclusive verdict.",
    )
    parser.add_argument(
        "--max-critical-ratio-gap",
        type=float,
        default=0.35,
        help="Max allowed absolute ratio gap for critical reasons when both sides observed.",
    )
    parser.add_argument(
        "--tp1-unobservable-policy",
        choices=("inconclusive", "pass"),
        default="inconclusive",
        help=(
            "Policy when TAKE_PROFIT_1 is unobservable in live snapshot while backtest has TP1. "
            "'inconclusive' keeps conservative default, 'pass' allows non-blocking progression."
        ),
    )
    parser.add_argument("--top-n", type=int, default=20)
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Return non-zero when verdict is not pass.",
    )
    return parser.parse_args(argv)


def parse_csv_tokens(raw: str) -> List[str]:
    values: List[str] = []
    seen: set[str] = set()
    for token in str(raw or "").split(","):
        value = token.strip()
        if not value:
            continue
        if value in seen:
            continue
        seen.add(value)
        values.append(value)
    return values


def normalize_reason(reason: str) -> str:
    value = str(reason or "").strip()
    return value if value else "unknown"


def normalize_market(market: str) -> str:
    value = str(market or "").strip()
    return value if value else "unknown"


def canonical_reason(reason: str) -> str:
    raw = normalize_reason(reason).strip().lower().replace("-", "_")
    aliases = {
        "stoploss": "STOP_LOSS",
        "stop_loss": "STOP_LOSS",
        "takeprofit1": "TAKE_PROFIT_1",
        "take_profit_1": "TAKE_PROFIT_1",
        "takeprofit2": "TAKE_PROFIT_2",
        "take_profit_2": "TAKE_PROFIT_2",
        "take_profit": "TAKE_PROFIT_2",
        "takeprofitfullduetominorder": "TAKE_PROFIT_FULL_DUE_TO_MIN_ORDER",
        "take_profit_full_due_to_min_order": "TAKE_PROFIT_FULL_DUE_TO_MIN_ORDER",
        "strategyexit": "STRATEGY_OR_RISK_EXIT",
        "strategy_exit": "STRATEGY_OR_RISK_EXIT",
        "riskmanagerexit": "STRATEGY_OR_RISK_EXIT",
        "risk_manager_exit": "STRATEGY_OR_RISK_EXIT",
        "backtesteod": "BACKTEST_EOD",
        "backtest_eod": "BACKTEST_EOD",
        "unknown": "UNKNOWN",
    }
    if raw in aliases:
        return aliases[raw]
    return raw.upper()


def reason_family(reason: str) -> str:
    canon = canonical_reason(reason)
    if canon in {"TAKE_PROFIT_2", "TAKE_PROFIT_FULL_DUE_TO_MIN_ORDER"}:
        return "TAKE_PROFIT_FINAL"
    return canon


def parse_dataset_market(dataset_name: str) -> str:
    # upbit_KRW_BTC_1m_12000.csv -> KRW-BTC
    name = str(dataset_name or "").strip()
    base = Path(name).name
    stem = base[:-4] if base.lower().endswith(".csv") else base
    tokens = stem.split("_")
    if len(tokens) >= 3 and tokens[0].lower() == "upbit":
        return f"{tokens[1]}-{tokens[2]}"
    return "unknown"


def canonicalize_market_reason_counter(counter: Dict[str, int]) -> Dict[str, int]:
    out: Dict[str, int] = {}
    for key, count in counter.items():
        market, reason = "unknown", "unknown"
        if "|" in str(key):
            market, reason = str(key).split("|", 1)
        mapped = f"{normalize_market(market)}|{canonical_reason(reason)}"
        out[mapped] = out.get(mapped, 0) + int(count)
    return out


def split_market_reason(counter: Dict[str, int]) -> Tuple[Dict[str, int], Dict[str, int]]:
    market_counts: Counter[str] = Counter()
    reason_counts: Counter[str] = Counter()
    for key, count in counter.items():
        market, reason = "unknown", "unknown"
        if "|" in str(key):
            market, reason = str(key).split("|", 1)
        market_counts[normalize_market(market)] += int(count)
        reason_counts[canonical_reason(reason)] += int(count)
    return dict(market_counts), dict(reason_counts)


def filter_counter_by_reason(counter: Dict[str, int], allowed_reasons: Iterable[str]) -> Dict[str, int]:
    allowed = {canonical_reason(x) for x in allowed_reasons}
    out: Dict[str, int] = {}
    for key, count in counter.items():
        market, reason = "unknown", "unknown"
        if "|" in str(key):
            market, reason = str(key).split("|", 1)
        canon = canonical_reason(reason)
        if canon not in allowed:
            continue
        out[f"{normalize_market(market)}|{canon}"] = int(count)
    return out


def aggregate_reason_counts_by_family(
    reason_counts: Dict[str, int],
    target_families: Iterable[str],
) -> Dict[str, int]:
    out: Counter[str] = Counter()
    family_set = {reason_family(x) for x in target_families}
    for reason, count in reason_counts.items():
        family = reason_family(reason)
        if family not in family_set:
            continue
        out[family] += int(count)
    return dict(out)


def build_delta_rows(counter_live: Dict[str, int], counter_backtest: Dict[str, int], top_n: int) -> List[Dict[str, Any]]:
    keys = sorted(set(counter_live.keys()) | set(counter_backtest.keys()))
    live_total = float(sum(max(0, int(v)) for v in counter_live.values()))
    backtest_total = float(sum(max(0, int(v)) for v in counter_backtest.values()))
    rows: List[Dict[str, Any]] = []
    for key in keys:
        live_count = max(0, int(counter_live.get(key, 0)))
        backtest_count = max(0, int(counter_backtest.get(key, 0)))
        rows.append(
            {
                "key": str(key),
                "live_count": live_count,
                "backtest_count": backtest_count,
                "delta_count": live_count - backtest_count,
                "live_ratio": (live_count / live_total) if live_total > 0.0 else 0.0,
                "backtest_ratio": (backtest_count / backtest_total) if backtest_total > 0.0 else 0.0,
            }
        )
    rows.sort(
        key=lambda row: (
            abs(int(row["delta_count"])),
            abs(float(row["live_ratio"]) - float(row["backtest_ratio"])),
        ),
        reverse=True,
    )
    return rows[: max(1, int(top_n))]


def load_live_market_reason_counts(audit: Dict[str, Any]) -> Dict[str, int]:
    snapshot = audit.get("live_exit_reason_snapshot", {})
    if not isinstance(snapshot, dict):
        return {}
    market_reason = snapshot.get("exit_market_reason_counts", {})
    if not isinstance(market_reason, dict):
        return {}
    out: Dict[str, int] = {}
    for key, value in market_reason.items():
        out[str(key)] = int(value)
    return out


def load_backtest_market_reason_counts_from_dataset_exit(audit: Dict[str, Any]) -> Dict[str, int]:
    out: Dict[str, int] = {}
    items = audit.get("dataset_results", [])
    if not isinstance(items, list):
        return out
    for item in items:
        if not isinstance(item, dict):
            continue
        market = parse_dataset_market(str(item.get("dataset", "")))
        reason_counts = item.get("exit_reason_counts", {})
        if not isinstance(reason_counts, dict):
            continue
        for reason, count in reason_counts.items():
            key = f"{market}|{normalize_reason(str(reason))}"
            out[key] = out.get(key, 0) + int(count)
    return out


def load_backtest_market_reason_counts_from_runtime_samples(audit: Dict[str, Any]) -> Dict[str, int]:
    out: Dict[str, int] = {}
    items = audit.get("dataset_results", [])
    if not isinstance(items, list):
        return out
    for item in items:
        if not isinstance(item, dict):
            continue
        market = parse_dataset_market(str(item.get("dataset", "")))
        runtime = item.get("runtime_trade_distribution", {})
        if not isinstance(runtime, dict):
            continue
        reason_counts = runtime.get("runtime_exit_reason_counts_in_samples", {})
        if not isinstance(reason_counts, dict):
            continue
        for reason, count in reason_counts.items():
            key = f"{market}|{normalize_reason(str(reason))}"
            out[key] = out.get(key, 0) + int(count)
    return out


def ratio(count: int, total: int) -> float:
    return (float(count) / float(total)) if int(total) > 0 else 0.0


def main(argv=None) -> int:
    args = parse_args(argv)
    audit_path = resolve_repo_path(args.audit_json)
    output_path = resolve_repo_path(args.output_json)

    payload = load_json_or_none(audit_path)
    if not isinstance(payload, dict):
        raise FileNotFoundError(f"audit json missing/invalid: {audit_path}")

    live_snapshot = payload.get("live_exit_reason_snapshot", {})
    if not isinstance(live_snapshot, dict):
        live_snapshot = {}

    ignore_reasons = [canonical_reason(x) for x in parse_csv_tokens(args.ignore_reasons)]
    critical_reasons = [canonical_reason(x) for x in parse_csv_tokens(args.critical_reasons)]
    top_n = max(1, int(args.top_n))
    min_live_core_exits = max(0, int(args.min_live_core_exits))
    min_backtest_core_exits = max(0, int(args.min_backtest_core_exits))
    max_critical_ratio_gap = max(0.0, float(args.max_critical_ratio_gap))
    tp1_unobservable_policy = str(args.tp1_unobservable_policy)
    live_partial_tp1_observable = bool(live_snapshot.get("partial_tp1_observable", False))

    live_raw = load_live_market_reason_counts(payload)
    backtest_dataset_raw = load_backtest_market_reason_counts_from_dataset_exit(payload)
    backtest_runtime_raw = load_backtest_market_reason_counts_from_runtime_samples(payload)
    backtest_source = (
        "dataset_exit_reason_counts"
        if int(sum(backtest_dataset_raw.values())) > 0
        else "runtime_trade_distribution_samples"
    )
    backtest_raw = backtest_dataset_raw if backtest_source == "dataset_exit_reason_counts" else backtest_runtime_raw

    live_canonical = canonicalize_market_reason_counter(live_raw)
    backtest_canonical = canonicalize_market_reason_counter(backtest_raw)
    live_market_counts, live_reason_counts_all = split_market_reason(live_canonical)
    backtest_market_counts, backtest_reason_counts_all = split_market_reason(backtest_canonical)

    all_core_reasons = sorted(set(critical_reasons))
    live_core = filter_counter_by_reason(live_canonical, all_core_reasons)
    backtest_core = filter_counter_by_reason(backtest_canonical, all_core_reasons)
    _, live_reason_counts_core_exact = split_market_reason(live_core)
    _, backtest_reason_counts_core_exact = split_market_reason(backtest_core)
    critical_reason_families: List[str] = []
    for item in critical_reasons:
        family = reason_family(item)
        if family in critical_reason_families:
            continue
        critical_reason_families.append(family)
    live_reason_counts_core = aggregate_reason_counts_by_family(
        live_reason_counts_core_exact,
        critical_reason_families,
    )
    backtest_reason_counts_core = aggregate_reason_counts_by_family(
        backtest_reason_counts_core_exact,
        critical_reason_families,
    )

    live_core_total = int(sum(live_reason_counts_core.values()))
    backtest_core_total = int(sum(backtest_reason_counts_core.values()))
    overlap_markets = sorted(set(live_market_counts.keys()) & set(backtest_market_counts.keys()))
    comparable = bool(live_core_total > 0 and backtest_core_total > 0 and overlap_markets)
    sample_size_ready = (
        live_core_total >= min_live_core_exits and backtest_core_total >= min_backtest_core_exits
    )

    allowed_findings: List[Dict[str, Any]] = []
    critical_findings: List[Dict[str, Any]] = []

    # Allowed difference: environment-specific backtest close reason.
    if "BACKTEST_EOD" in ignore_reasons:
        backtest_eod = int(backtest_reason_counts_all.get("BACKTEST_EOD", 0))
        live_eod = int(live_reason_counts_all.get("BACKTEST_EOD", 0))
        if backtest_eod > 0 and live_eod == 0:
            allowed_findings.append(
                {
                    "type": "allowed_reason_difference",
                    "reason": "BACKTEST_EOD",
                    "live_count": live_eod,
                    "backtest_count": backtest_eod,
                    "note": "Backtest-only session-end close is expected in offline replay.",
                }
            )

    if not overlap_markets:
        allowed_findings.append(
            {
                "type": "inconclusive_no_overlap_market",
                "note": "No overlap markets between live and backtest exit samples.",
            }
        )

    if comparable and not sample_size_ready:
        allowed_findings.append(
            {
                "type": "inconclusive_low_sample",
                "live_core_total": live_core_total,
                "backtest_core_total": backtest_core_total,
                "min_live_core_exits": min_live_core_exits,
                "min_backtest_core_exits": min_backtest_core_exits,
            }
        )

    # Critical gap detection: must-match reason coverage + ratio drift.
    tp1_unobservable_gap = (
        comparable
        and sample_size_ready
        and (not live_partial_tp1_observable)
        and int(backtest_reason_counts_core.get("TAKE_PROFIT_1", 0)) > 0
        and int(live_reason_counts_core.get("TAKE_PROFIT_1", 0)) == 0
    )
    live_tp_final_min_order_exact = int(
        live_reason_counts_core_exact.get("TAKE_PROFIT_FULL_DUE_TO_MIN_ORDER", 0)
    )
    backtest_tp_final_exact = int(backtest_reason_counts_core.get("TAKE_PROFIT_FINAL", 0))
    tp1_collapsed_to_min_order_full_exit = (
        tp1_unobservable_gap
        and live_tp_final_min_order_exact > 0
        and backtest_tp_final_exact > 0
    )
    if tp1_collapsed_to_min_order_full_exit:
        allowed_findings.append(
            {
                "type": "allowed_tp1_collapsed_to_full_due_to_min_order",
                "live_tp1_count": int(live_reason_counts_core.get("TAKE_PROFIT_1", 0)),
                "backtest_tp1_count": int(backtest_reason_counts_core.get("TAKE_PROFIT_1", 0)),
                "live_tp_final_min_order_count_exact": live_tp_final_min_order_exact,
                "backtest_tp_final_count": backtest_tp_final_exact,
                "note": (
                    "Live TP1 may collapse into TAKE_PROFIT_FULL_DUE_TO_MIN_ORDER "
                    "when partial TP is not executable under min-order constraints."
                ),
            }
        )
        tp1_unobservable_gap = False
    for reason in critical_reason_families:
        live_count = int(live_reason_counts_core.get(reason, 0))
        backtest_count = int(backtest_reason_counts_core.get(reason, 0))
        if live_count == 0 and backtest_count == 0:
            continue

        if comparable and sample_size_ready:
            if live_count == 0 or backtest_count == 0:
                if reason == "TAKE_PROFIT_1" and tp1_collapsed_to_min_order_full_exit:
                    # Live TP1 can collapse into full close under min-order constraints.
                    continue
                if (
                    reason == "TAKE_PROFIT_1"
                    and backtest_count > 0
                    and live_count == 0
                    and not live_partial_tp1_observable
                    and not tp1_collapsed_to_min_order_full_exit
                ):
                    tp1_unobservable_gap = True
                    allowed_findings.append(
                        {
                            "type": "inconclusive_tp1_unobservable",
                            "reason": reason,
                            "live_count": live_count,
                            "backtest_count": backtest_count,
                            "note": (
                                "Live log snapshot has no TP1-observable markers. "
                                "Collect TP1-observable logs before declaring critical mismatch."
                            ),
                        }
                    )
                    continue
                critical_findings.append(
                    {
                        "type": "critical_reason_missing",
                        "reason": reason,
                        "live_count": live_count,
                        "backtest_count": backtest_count,
                    }
                )
                continue
            live_ratio = ratio(live_count, live_core_total)
            backtest_ratio = ratio(backtest_count, backtest_core_total)
            if tp1_unobservable_gap and reason != "TAKE_PROFIT_1":
                # When TP1 is unobservable in live logs, core-ratio denominators
                # become biased. Defer ratio-drift verdict until TP1-observable
                # evidence is available.
                continue
            ratio_gap = abs(live_ratio - backtest_ratio)
            if ratio_gap > max_critical_ratio_gap:
                critical_findings.append(
                    {
                        "type": "critical_reason_ratio_drift",
                        "reason": reason,
                        "live_ratio": live_ratio,
                        "backtest_ratio": backtest_ratio,
                        "ratio_gap": ratio_gap,
                        "max_critical_ratio_gap": max_critical_ratio_gap,
                    }
                )

    if not comparable:
        verdict = "inconclusive"
        next_step_hint = "collect_overlap_market_exit_samples_for_should_exit_surface"
    elif not sample_size_ready:
        verdict = "inconclusive"
        next_step_hint = "increase_core_exit_sample_size_before_should_exit_verdict"
    elif critical_findings:
        verdict = "fail"
        next_step_hint = "investigate_should_exit_mapping_or_trigger_drift"
    elif tp1_unobservable_gap:
        if tp1_unobservable_policy == "pass":
            verdict = "pass"
            next_step_hint = "collect_tp1_observable_live_exit_logs_for_stronger_confidence"
            allowed_findings.append(
                {
                    "type": "tp1_unobservable_pass_override",
                    "policy": tp1_unobservable_policy,
                    "note": (
                        "TP1 mismatch treated as non-blocking because TP1 is not observable in live logs. "
                        "Collect TP1-observable evidence to remove this override."
                    ),
                }
            )
        else:
            verdict = "inconclusive"
            next_step_hint = "collect_tp1_observable_live_exit_logs_before_tp1_gap_decision"
    else:
        verdict = "pass"
        next_step_hint = "should_exit_surface_parity_stable"

    report: Dict[str, Any] = {
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "inputs": {
            "audit_json": str(audit_path),
            "backtest_counts_source": backtest_source,
            "ignore_reasons": ignore_reasons,
            "critical_reasons": critical_reasons,
            "critical_reason_families": critical_reason_families,
            "live_partial_tp1_observable": live_partial_tp1_observable,
            "min_live_core_exits": min_live_core_exits,
            "min_backtest_core_exits": min_backtest_core_exits,
            "max_critical_ratio_gap": max_critical_ratio_gap,
            "tp1_unobservable_policy": tp1_unobservable_policy,
            "top_n": top_n,
        },
        "parity_boundary": {
            "must_match_core_surface": [
                "STOP_LOSS / TAKE_PROFIT / STRATEGY_OR_RISK_EXIT reason semantics",
                "core reason coverage on overlap markets",
                "core reason ratio stability under sufficient sample size",
                "TAKE_PROFIT_2 and TAKE_PROFIT_FULL_DUE_TO_MIN_ORDER treated as TAKE_PROFIT_FINAL family",
            ],
            "allowed_runtime_differences": [
                "BACKTEST_EOD backtest-only session-end close",
                "timestamp/source/order-id runtime transport differences",
                "low-sample or no-overlap-market inconclusive states",
            ],
        },
        "live": {
            "market_counts": live_market_counts,
            "reason_counts_all": live_reason_counts_all,
            "reason_counts_core": live_reason_counts_core,
            "reason_counts_core_exact": live_reason_counts_core_exact,
            "core_total_exits": live_core_total,
        },
        "backtest": {
            "source": backtest_source,
            "market_counts": backtest_market_counts,
            "reason_counts_all": backtest_reason_counts_all,
            "reason_counts_core": backtest_reason_counts_core,
            "reason_counts_core_exact": backtest_reason_counts_core_exact,
            "core_total_exits": backtest_core_total,
        },
        "comparison": {
            "comparable": comparable,
            "sample_size_ready": sample_size_ready,
            "tp1_collapsed_to_min_order_full_exit": tp1_collapsed_to_min_order_full_exit,
            "overlap_markets": overlap_markets,
            "core_reason_delta_rows": build_delta_rows(live_reason_counts_core, backtest_reason_counts_core, top_n),
            "market_delta_rows": build_delta_rows(live_market_counts, backtest_market_counts, top_n),
            "market_reason_core_delta_rows": build_delta_rows(live_core, backtest_core, top_n),
        },
        "allowed_findings": allowed_findings,
        "critical_findings": critical_findings,
        "verdict": verdict,
        "next_step_hint": next_step_hint,
    }

    dump_json(output_path, report)
    print(f"[ShouldExitParity] wrote {output_path}")
    print(
        "[ShouldExitParity] verdict="
        f"{verdict} comparable={str(comparable).lower()} sample_size_ready={str(sample_size_ready).lower()} "
        f"critical_findings={len(critical_findings)} next_step_hint={next_step_hint}"
    )

    if args.strict and verdict != "pass":
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
